// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClakb5nj3zT0URgbrtC6v35OmcTB9yMdY',
    appId: '1:618091922594:web:a61e187aac70e8afaa43fb',
    messagingSenderId: '618091922594',
    projectId: 'cap-telephonie',
    authDomain: 'cap-telephonie.firebaseapp.com',
    storageBucket: 'cap-telephonie.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDCEU3L3hks-9BjAlZcUrzWTKHcurtNqk',
    appId: '1:618091922594:android:8ceaa8f2d93e259baa43fb',
    messagingSenderId: '618091922594',
    projectId: 'cap-telephonie',
    storageBucket: 'cap-telephonie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfnxLkk0SQ9r9tNDEMjM3SlHiA0LNwwmE',
    appId: '1:618091922594:ios:e1d75dac3d01e2e8aa43fb',
    messagingSenderId: '618091922594',
    projectId: 'cap-telephonie',
    storageBucket: 'cap-telephonie.firebasestorage.app',
    iosBundleId: 'com.telephoniecap.telephonieCap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfnxLkk0SQ9r9tNDEMjM3SlHiA0LNwwmE',
    appId: '1:618091922594:ios:e1d75dac3d01e2e8aa43fb',
    messagingSenderId: '618091922594',
    projectId: 'cap-telephonie',
    storageBucket: 'cap-telephonie.firebasestorage.app',
    iosBundleId: 'com.telephoniecap.telephonieCap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClakb5nj3zT0URgbrtC6v35OmcTB9yMdY',
    appId: '1:618091922594:web:abcc1a9a638fafe3aa43fb',
    messagingSenderId: '618091922594',
    projectId: 'cap-telephonie',
    authDomain: 'cap-telephonie.firebaseapp.com',
    storageBucket: 'cap-telephonie.firebasestorage.app',
  );
}
